.\" Manpage for cchat.
.\" Contact despoinidisk@gmail.com to correct errors or typos.
.TH man 8 "01 Feb 2024" "1.0.2" "cchat man page"

.SH NAME

cchat \- chat via the terminal 

.SH SYNOPSIS

cchat [COMMAND] [-a|--address] [-p|--port]

.SH DESCRIPTION

cchat is a simple chat application for the terminal

.SH COMMANDS

serve                Start the server

connect              Connect to a server

.SH OPTIONS

-a --address         Specify the ip address to serve or connect to

-p --port            Specify the port

-v --version         Prints the version of the executable

-u --username        Specify your username

.SH EXAMPLES

Serve: cchat serve -a 127.0.0.1 -p 1234

Connect: cchat connect -a 127.0.0.1 -p 1234 -u user123

.SH BUGS

No known bugs.

.SH AUTHOR

Konstantinos Despoinidis (despoinidisk@gmail.com)
